import type { Metadata } from "next";
import { Geist, Geist_Mono,Geologica } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { Toaster } from 'sonner'
import { Footer } from "@/components/Footer";


const geologica = Geologica({
  subsets: ['latin'],
  weight: ['400', '700'], // or add more weights as needed
  variable: '--font-geologica',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" >
        <body className={`${geologica.variable} antialiased`}>
           <Toaster position="top-center" richColors closeButton />
          <Navbar/>
          {children}
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
